### PR TITLE
Fix for #87 — force `update_datetime` to be a datetime

### LINKED ISSUE #87: Inconsistent column types prevent `bind_rows()` in `npn_get_data_by_year()`
``` r
library(rnpn)
endpoint <- "/observations/getObservations.ndjson?"
query <- list(
  request_src = "Unit%20Test",
  climate_data = "0",
  `species_id[1]` = "6"
)
rnpn:::npn_get_data_by_year(endpoint = endpoint, query = query, years = c("2010", "2013"))
#> Error in `dplyr::bind_rows()`:
#> ! Can't combine `..1$update_datetime` <double> and `..2$update_datetime` <character>.
```

<sup>Created on 2025-01-28 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Looks like `update_datetime` column is sometimes all missing data and gets interpreted as numeric instead of a datetime.

### PR DESCRIPTION
**Pull request by Aariq**
Fixes #87. Unfortunately more of these could pop up in the future.  If they do, I'll try to come up with a more generic fix.  Didn't update NEWS because I'm pretty sure this bug was introduced in this version.

### CODE REVIEW

File: R/npn_data_download.R [hunk 1]
```diff
@@ -719,10 +731,22 @@ npn_get_data <- function(url,
...
-      dplyr::mutate(dplyr::across(dplyr::where(is.character),
-                                  \(x) ifelse(x == "-9999", NA_character_, x)))
+      dplyr::mutate(
+        dplyr::across(dplyr::where(is.numeric),
+                      function(x) ifelse(x == -9999, NA_real_, x))
+      ) %>%
+      dplyr::mutate(
+        dplyr::across(dplyr::where(is.character),
+                      function(x) ifelse(x == "-9999", NA_character_, x))
+      ) %>%
```
Comment (Aariq) [inline R/npn_data_download.R:741]: The change from `\(x)` to `function(x)` is because the shorthand `\(x)` is only available in more recent versions of R, but defines an anonymous function identically to `function(x)`

File: R/npn_data_download.R [hunk 2]
```diff
@@ -719,10 +731,22 @@ npn_get_data <- function(url,
...
+      #handle some columns that may be read in as the wrong type if they happen
+      #to be all NAs (#87). `any_of()` is used because not all endpoints will
+      #return these columns!
+      dplyr::mutate(
+        dplyr::across(dplyr::any_of("update_datetime"),
+                      function(x) as.POSIXct(x, tz = "UTC")),
```
Comment (Aariq) [inline R/npn_data_download.R:747]: Not sure what the timezone should be here or if it matters.  Could also just make this column character and leave it up to the user to figure out the timezone if they care.

File: R/npn_data_download.R [hunk 3]
```diff
@@ -719,10 +731,22 @@ npn_get_data <- function(url,
...
+        dplyr::across(dplyr::any_of("intensity_value"), as.character)
```
Comment (Aariq) [inline R/npn_data_download.R:748]: I've found that this column is sometimes numbers, but also sometimes things like "3 to 10".  Do you happen to know if `abundance_value` is the same?

File: R/npn_data_download.R [hunk 4]
```diff
@@ -689,6 +689,18 @@ npn_get_data_by_year <- function(endpoint,
...
+#'   url = "https://services.usanpn.org/npn_portal//observations/getObservations.ndjson?",
+#'   query = list(
+#'     request_src = "Unit%20Test",
+#'     climate_data = "0",
+#'     `species_id[1]` = "6",
+#'     start_date = "2010-01-01",
+#'     end_date = "2010-12-31"
+#'   )
+#' )
+#' }
```
Comment (Aariq) [inline R/npn_data_download.R:703]:
```suggestion
#' @examples \dontrun{
#' npn_get_data(
#'   url = "https://services.usanpn.org/npn_portal//observations/getObservations.ndjson?",
#'   query = list(
#'     request_src = "Unit%20Test",
#'     climate_data = "0",
#'     `species_id[1]` = "6",
#'     start_date = "2010-01-03",
#'     end_date = "2010-12-31"
#'   )
#' )
#' }
```

File: R/npn_data_download.R (hunk 3 above)
Comment (jeffswitzer) [reply R/npn_data_download.R:748]: I just checked the Abundance Value table and some random examples are "50-74%", "Peak pollen", "Moderate".

Comment (Aariq) [reply R/npn_data_download.R:748]: Ah ok,  I'll make a separate PR to make this change since this one is already merged
```suggestion
        dplyr::across(dplyr::any_of("intensity_value", "abundance_valuue"), as.character)
```
